# Generated by Django 5.2.1 on 2025-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0002_rename_user_user_first_remove_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=2, upload_to='image'),
            preserve_default=False,
        ),
    ]
